import { Geist, Geist_Mono,Roboto, Inter,Sora,Figtree } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
 variable: "--font-roboto",
subsets: ["latin"],
}); 
const inter = Inter({
 variable: "--font-inter",
subsets: ["latin"],
}); 

const sora = Sora({
 variable: "--font-sora",
subsets: ["latin"],
}); 

const figtree = Figtree({
 variable: "--font-figtree",
subsets: ["latin"],
}); 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${inter.variable} ${sora.variable} ${figtree.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
